Switch to esm.sh source for handlebars package
Because dev.jspm.io has issues and installs are erroring

```
error: Import 'https://dev.jspm.io/npm:source-map@0.6?dew' failed: 500 Internal Server Error
    at https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/code-gen.dew.js:2:41
```